project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - text: "<img src='img/logo.png' alt='Logo' style='height:30px; vertical-align: middle;'> Celeste Portfolio"
        href: index.qmd
      - text: Home
        href: index.qmd
      - text: My Project
        href: my-project.qmd
      - text: About Me
        href: about.qmd
      - text: Reflection
        href: reflection.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true
